### ISSUE TITLE
Getting notification data

### ISSUE THREAD

**Issue by tf** [pushpad/pushpad-ruby#3]
It would be nice if the library allowed getting notification data via the `GET /notifications/NOTIFICATION_ID` REST API endpoint. In particular, this would be useful to get statistics data like `successfully_sent_count` or `open_count`.

I could imagine the following interface based on a `find` method and further attribute readers.

```ruby
notification = Pushpad::Notification.find(id)
notification.open_count # => 4
```
Then it would probably make sense to store the attributes that are currently the return value of `deliver_to`:
```ruby
notification = Pushpad::Notification.new({
  body: "Hello world!",
  title: "Website Name"
})

notification.deliver_to(user)
notification.id # => 1000
notification.scheduled_count #=> 10
```
One thing to consider here is that the `Notification` class currently is more like a notification factory or builder. Calling `deliver_to` multiple times creates multiple notifications with different ids. I'm not sure if this is an edge case that should just be ignored by overwriting the `id` attribute in this case. Alternatively, one could raise an error when `deliver_to` is called and an `id` is already present, but that would be a breaking change to the API.

To circumvent this issue, we could also consider adding a whole new class, e.g. `DeliveredNotification`, which provides the `find` and reader methods. That way the concerns of delivering notifications and getting data about past notifications would be separated cleanly. `deliver_to` could even return a `DeliveredNotification` which could implement `[]` to stay compatible with the prior hashed based API.

**Comment by collimarco** [comment]
The behavior for the `find`method is ok!

For `deliver_to` we have to consider that the data returned by the API is not necessarily related to the notification (e.g. it can return the list of the user IDs that are actually subscribed, some information about rate limit, usage quota, etc.) and it cannot be wrapped as an attribute of the Notification class. Thus **the raw JSON must always be returned** by that method.

However it's ok to introduce some syntactic sugar for the data that can be represented by an attribute of the Notification class.

> One thing to consider here is that the Notification class currently is more like a notification factory or builder. Calling deliver_to multiple times creates multiple notifications with different ids. I'm not sure if this is an edge case that should just be ignored by overwriting the id attribute in this case. 

This is a good point, but I would go for the simplest solution: just **ignore multiple calls (i.e. do not raise errors) and overwrite the id attribute** (in the future we may as well overwrite uids and tags if we add that attributes to the Notification class - `deliver_to` and `broadcast` are offered as separate methods because they behave slightly differently and the API returns different values in the JSON).

**Comment by tf** [comment]
+1 for simplicity. But the following case could be slightly confusing then:
```ruby
notification = Pushpad::Notification.find(id)
notification.deliver_to(user)
notification.id # => new id
```

**Comment by collimarco** [comment]
Yes, your example can be slightly confusing, but it's an edge case and **I can't see any better option**:

- raising errors, as you said, would be a **breaking change**
- DeliveredNotification would be 99% similar to a Notification and on the server side **Pushpad has just a Notification model**

Similar to the second approach (DeliveredNotification), but more lightweight would be a `readonly` or `saved` flag on a Notification... but then, again, for consistency, we would have to add it also after a `deliver_to`, which is something we don't want (i.e. breaking change).

I would say: ignore multiple calls (i.e. do not raise errors) and overwrite the id attribute. If you like the idea, put a readonly flag on the notification **only when it's retrieved with `find`** (not when `deliver_to` is called).
